### ISSUE TITLE
Update trm.fredhutch.org

### ISSUE THREAD

**Issue by vsriram24** [FredHutch/trm-calculator#21]
Officially deploy the Shiny app to https://trm.fredhutch.org (pending approval)

**Comment by monicagerber** [comment]
I found out it should be deployed automatically through CI/CD but we need to update the docker file with the new package dependencies: https://github.com/FredHutch/trm-calculator/blob/main/Dockerfile#L4


https://sciwiki.fredhutch.org/compdemos/shiny/#request-deployment-service-from-scicomp

**Comment by monicagerber** [comment]
library(shiny)
 library(shinythemes)
 library(shinydashboard)
-library(DT)
+library(shinyvalidate)
 library(dplyr)
+library(gt)
+library(gtExtras)
